fieldLayouts:
  acc4a579-4344-4aa3-ad54-09334cc9e064:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 404fa88b-1fb0-4098-b26f-4e9d8a50e596
            warning: null
            width: 100
          -
            fieldUid: 6f88735f-d41c-4e41-9689-c5bacd8289fc # Parameter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f401cab6-a5be-4e39-aaf3-6e4f41cd1378
            warning: null
            width: 100
        name: Content
        uid: 09f46091-a666-42e3-8e51-b2c79fcd3e9c
handle: home
hasTitleField: false
name: Home
section: 0c18c298-5b23-4595-87b9-080cf00b6123 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
