columnSuffix: null
contentColumnType: string
fieldGroup: 8bdcfa7c-982f-47df-bd2e-bf48e43de9d6 # Common
handle: parameter
instructions: null
name: Parameter
searchable: false
settings:
  contentTable: '{{%matrixcontent_parameter}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: siteGroup
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
