defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  ae64ce60-e2e8-4297-a182-841461882e2e: # PruneRevisionsMatrix
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  d19e4e4d-f9ca-462a-8570-65e50bd96734: # PruneRevisionsMatrixDE
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
